### ISSUE TITLE
Testing AC007E-01

### ISSUE THREAD

**Issue by albertofralbe** [Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant#17]
Hi there, just wanted to share that AC007E-01 wallbox (single-phase model, with EMS mode paired with SH6.0RS) seems to be working fine with this integration. I will dive deeper later on all the various functions
<img width="510" alt="Screenshot 2024-05-09 at 09 23 50" src="https://github.com/Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant/assets/82574830/f60bc16e-e6e7-4881-a1f2-f59e63c75cfd">

**Comment by albertofralbe** [comment]
Reported device type code: 17282

**Comment by SunnyCrockett** [comment]
Thanks for the information!
I am using type code 8410 (AC011E-01) with SH10RT and I am also able to receive information and start/stop charging since I updated my whole components to the newest firmware.

**Comment by albertofralbe** [comment]
Charging works but I can't wrap my head around how to enable the solar surplus mode "Eco Charging" from HA. I'm currently experiencing an outage of the iSolarCloud service so I definitely want to get rid of it asap. Thanks

**Comment by SunnyCrockett** [comment]
Have a look at issue https://github.com/Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant/issues/13, maybe one us will geht this to work soon
