### ISSUE TITLE
All Entities in Dashboard unavailable

### ISSUE THREAD

**Issue by hboltz** [Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant#22]
I added the 3 rows to to the existing ones in secrets.yaml:

sungrow_modbus_host_ip: 172.17.2.107 
sungrow_modbus_port: 502
sungrow_modbus_slave: 1 

wallbox_modbus_host_ip: 172.17.2.107  
wallbox_modbus_port: 502 
wallbox_modbus_slave: 2 

Then I added the dashboard example from SunnyCrocket to one of my dashboards, but unfortunately I don't get the entities - all are unavailable in dashboard. Any hint for me?

**Comment by hboltz** [comment]
in the logs I found a important hint:

Modbus SungrowACx host/port 172.17.2.107_502 is duplicate, not loaded!

How should I configure the secrets.yaml?

**Comment by hboltz** [comment]
now I changed the secrets.yaml to following configuration:

sungrow_modbus_host_ip: 172.17.2.107
sungrow_modbus_port: 502
sungrow_modbus_slave: 1
wallbox_modbus_slave: 2

and I tried to work with only 1 modbus.yaml file and I tried to merge the modbus_sungrow.yaml and the modbus_wallbox.yaml  in the modbus_sungrow.yaml - it's both Sungrow stuff. But the entities are still unavailable.

**Comment by hboltz** [comment]
I checked the SlaveID once again but "2" is the right one. The Sungrow inverter has the "1".

I also tried to get the modbus communication over two adapters of the inverter: I used the rear LAN port for the inverter itself and the WiNet-S port for the wallbox, but this crashed my whole configuration and I had to rollback to the last backup.

So, what is the recommendation? From my understanding, I should install the modbus proxy, which connects to the LAN port of the inverter. In HA I have to configure the secrets.yaml like in the beginning - only the host IPs should point to the modbus proxy. And at least, I'll have 2 files under "integrations" folder: modbus_sungrow.yaml for the inverter configuration and the modbus_wallbox.yaml for the wallbox. Is this correct?

**Comment by SunnyCrockett** [comment]
In my setup, I have configured sungrow_modbus_host_ip to the IP of the inverter and wallbox_modbus_host_ip to the IP of the dongle (they have different IPs). My recommendationis to do it that way.

If you want to use the dongle only, you have to configure two ModBus TCP ports with the ModBus TCP proxy. One for the Sungrow integration and one for the wallbox integration. Both ports should point to the dogles ModBus TCP IP and port.

Two files in the integrations folder is correct.

**Comment by hboltz** [comment]
what do you mean with dongle - the WiNet-S Interface?

**Comment by hboltz** [comment]
I tried it once again with your recommended configuration:

Inverter via LAN Port IP and SlaveID1
Wallbox via WiNet-S Port IP and SlaveID2

Now it's working but I found 2 missing entities in the dashboard:

This dashboard refers to the following entities that are unknown to Home Assistant:

automation.wallbox_charger_remote_control_cmd
input_select.set_wb_remote_control

Any help is welcome!

**Comment by SunnyCrockett** [comment]
> what do you mean with dongle - the WiNet-S Interface?

yes

>I checked the [modbus_wallbox.yaml](https://github.com/Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant/blob/main/modbus_wallbox.yaml) and I didn't find these 2 entities. Did you extend the modbus_wallbox.yaml to get them? What am I making wrong?

they were removed in the past, I have updated my dashboard snippet in [issue 11](https://github.com/Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant/issues/11).

**Comment by hboltz** [comment]
ok - I removed the 2 entities now.

**Comment by hboltz** [comment]
wallbox is integrated in HA now
