### ISSUE TITLE
Charging start/end time is not correct

### ISSUE THREAD

**Issue by SunnyCrockett** [Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant#6]
The values I get for "Charging start time" and "Charging end time" are not correct:
![image](https://github.com/Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant/assets/153714968/b3f64a59-5c2b-491a-97a3-158ad39a1f3b)
![image](https://github.com/Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant/assets/153714968/fca289c1-cade-41d1-8cea-5d3199bca66f)
I tried to get the correct values with modbus-cli and was successful with the following:
`modbus dongle:502 -s 3 i@21319/I --byte-order=mixed`
`Parsed 0 registers definitions from 1 files`
`21319: 1707007290 0x65bedd3a`
`modbus dongle:502 -s 3 i@21317/I --byte-order=mixed`
`Parsed 0 registers definitions from 1 files`
`21317: 1706937153 0x65bdcb41`

Those values are UNIX timestamps and could be converted to date/time. Unfortunately, I dont know how to configure the "--byte-order=mixed" option in HA yaml. Do you know how to do that?

Thanks & regards
Sunny

**Comment by Louisbertelsmann** [comment]
I‘ll figure something out. I did it some time ago, but a lot has changed. I also don‘t have that config anymore.

**Comment by Louisbertelsmann** [comment]
You might want to have a look at the swap option from homeassistant. There are a few options, but I don‘t know if the needed one is there.

**Comment by SunnyCrockett** [comment]
Thanks for the hint with swap option, I have created a pull request with a fix that works for me:
![image](https://github.com/Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant/assets/153714968/d344593f-815e-47e0-ad7e-bb1d89b0dc44)

**Comment by Louisbertelsmann** [comment]
Ok, thanks a lot. I will update the wiki and put it out of beta.

**Comment by btota** [comment]
perfect guys! Same for other uint32 values, do we need to add swap:word to all uint32 registers? (ie. "Maximum charging power"|"Total energy")
![grafik](https://github.com/Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant/assets/71133306/67e0ed16-d879-4dec-a203-237a175ef28a)
![grafik](https://github.com/Louisbertelsmann/Sungrow-Wallbox-Modbus-HomeAssistant/assets/71133306/0a635804-af36-45c0-a133-5dc07099df88)

```ruby 
pull request
- name: Maximum charging power
        unique_id: wb1_maximum_charging_power
        slave: !secret wallbox_modbus_slave
        address: 21272 # reg 21273
        input_type: input
        data_type: uint32
        swap: word
        precision: 1
        unit_of_measurement: W
        device_class: Power
        scale: 1
        scan_interval: 60

      - name: Total energy A
        unique_id: wb1_total_energy_a
        slave: !secret wallbox_modbus_slave
        address: 21299 # reg 21300
        input_type: input
        data_type: uint32
        swap: word
        precision: 1
        unit_of_measurement: Wh
        device_class: Energy
        scale: 1
        scan_interval: 600

**Comment by btota** [comment]
Working mode is input_type: holding

```ruby
pull request
- name: Working mode
        unique_id: wb1_working_mode
        slave: !secret wallbox_modbus_slave
        address: 21262 # reg 21263
        input_type: holding #input
        data_type: uint16
        scan_interval: 600

**Comment by SunnyCrockett** [comment]
I have created a new pull request with some fixes and a new template.

**Comment by Louisbertelsmann** [comment]
It doesn't look like that exists, at least not in the official documentation.

**Comment by btota** [comment]
Not really - maybe an automation for each scenario is needed, can one also modbusscan with modbus-cli [0-248]?

**Comment by btota** [comment]
Wrong datetime (as_local):

```ruby
pull request
template:
  - sensor:
      - name: Charging start time
        unique_id: wb1_charging_start_time
        state: >
          {{ as_local(as_datetime(states.sensor.charging_start_time_raw.state)).strftime("%d.%m.%Y %H:%M") }}

      - name: Charging end time
        unique_id: wb1_charging_end_time
        state: >
          {{ as_local(as_datetime(states.sensor.charging_end_time_raw.state)).strftime("%d.%m.%Y %H:%M") }}

needs to be changed to

template:
  - sensor:
      - name: Charging start time
        unique_id: wb1_charging_start_time
        state: >
          {{ (as_datetime(states.sensor.charging_start_time_raw.state)).strftime("%d.%m.%Y %H:%M") }}
      - name: Charging end time
        unique_id: wb1_charging_end_time
        state: >
          {{ (as_datetime(states.sensor.charging_end_time_raw.state)).strftime("%d.%m.%Y %H:%M") }}

**Comment by SunnyCrockett** [comment]
Without the as_local, it is in utc0. I am in utc+1 and wanted it shown like in the iCloudSolar app. Whats your timezone in HA?

**Comment by btota** [comment]
Weird. Timezone on HA is gmt+01:00 Berlin.  Using as_local caused right timestamp +1 hour :)
